# Generated by Django 2.0.5 on 2018-07-17 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drf_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'verbose_name': 'Bank Account', 'verbose_name_plural': 'Bank Accounts'},
        ),
        migrations.AlterModelOptions(
            name='bankmaster',
            options={'verbose_name': 'Bank', 'verbose_name_plural': 'Banks'},
        ),
        migrations.AlterModelOptions(
            name='creditcard',
            options={'verbose_name': 'Credit Card', 'verbose_name_plural': 'Credit Cards'},
        ),
        migrations.AlterModelOptions(
            name='debitcard',
            options={'verbose_name': 'Debit Card', 'verbose_name_plural': 'Debit Cards'},
        ),
        migrations.AlterUniqueTogether(
            name='creditcard',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='debitcard',
            unique_together=set(),
        ),
    ]
